version: '3.8'

services:
  go_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: comment-tree
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - comment-tree-network

  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - comment-tree-network

networks:
  comment-tree-network:
    driver: bridge